image: sbtscala/scala-sbt:eclipse-temurin-jammy-19.0.1_10_1.9.4_2.13.11

stages:
  - compile
  - test

variables:
  SBT_OPTS: "-Xmx1G -XX:MaxMetaspaceSize=512m -XX:ReservedCodeCacheSize=512m"

before_script:
  - sbt clean update

compile:
  stage: compile
  script:
    - sbt compile

test:
  stage: test
  only:
    - /^solution-.*/
  script:
    - sbt hw
